import type {
  VlanConfig,
  VlanNode,
  VlanLink,
  VlanDefinition,
  VlanTopologyPresetId,
  VlanScenarioId,
} from "./vlan.types";

export const DEFAULT_VLANS: VlanDefinition[] = [
  {
    vlanId: 1,
    name: "DEFAULT",
    color: "#64748b", // Slate
    subnet: "192.168.1.0/24",
    gatewayIp: "192.168.1.1",
    description: "Default management VLAN for untagged system traffic.",
  },
  {
    vlanId: 10,
    name: "ENGINEERING",
    color: "#3b82f6", // Blue
    subnet: "192.168.10.0/24",
    gatewayIp: "192.168.10.1",
    description: "High-throughput development and engineering workstations.",
  },
  {
    vlanId: 20,
    name: "SALES",
    color: "#10b981", // Emerald
    subnet: "192.168.20.0/24",
    gatewayIp: "192.168.20.1",
    description: "Sales, marketing, and business operations segment.",
  },
  {
    vlanId: 30,
    name: "EXECUTIVE",
    color: "#a855f7", // Purple
    subnet: "192.168.30.0/24",
    gatewayIp: "192.168.30.1",
    description: "High-security executive and finance department.",
  },
  {
    vlanId: 99,
    name: "MGMT_NATIVE",
    color: "#f59e0b", // Amber
    subnet: "192.168.99.0/24",
    gatewayIp: "192.168.99.1",
    description: "Isolated out-of-band management and trunk native transit.",
  },
];

export const defaultVlanConfig: VlanConfig = {
  topologyPreset: "multi_vlan_access_switch",
  scenarioId: "intra_vlan_broadcast_isolation",
  sourceNodeId: "pc-1",
  targetNodeId: "pc-2",
  nativeVlanId: 1,
  trunkAllowedVlans: [1, 10, 20, 30],
  routingMode: "none",
  enableDoubleTagging: false,
  tagNativeVlan: false,
};

// ─── Preset 1: Multi-VLAN Single Access Switch ──────────────────────────────
export const ACCESS_SWITCH_NODES: VlanNode[] = [
  {
    id: "pc-1",
    name: "PC 1 (Eng-A)",
    label: "Eng-PC1",
    type: "host",
    ipAddress: "192.168.10.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:01",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 100, y: 100 },
  },
  {
    id: "pc-2",
    name: "PC 2 (Eng-B)",
    label: "Eng-PC2",
    type: "host",
    ipAddress: "192.168.10.20",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:02",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 100, y: 280 },
  },
  {
    id: "sw-1",
    name: "Access Switch 1",
    label: "SW-Access1",
    type: "switch",
    ipAddress: "192.168.1.254",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:01",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 320, y: 190 },
    ports: [
      {
        id: "sw1-fa0/1",
        name: "Fa0/1",
        switchId: "sw-1",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-1",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-fa0/2",
        name: "Fa0/2",
        switchId: "sw-1",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-2",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-fa0/3",
        name: "Fa0/3",
        switchId: "sw-1",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-3",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-fa0/4",
        name: "Fa0/4",
        switchId: "sw-1",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-4",
        connectedPortName: "eth0",
      },
    ],
  },
  {
    id: "pc-3",
    name: "PC 3 (Sales-A)",
    label: "Sales-PC3",
    type: "host",
    ipAddress: "192.168.20.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:03",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 540, y: 100 },
  },
  {
    id: "pc-4",
    name: "PC 4 (Sales-B)",
    label: "Sales-PC4",
    type: "host",
    ipAddress: "192.168.20.20",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:04",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 540, y: 280 },
  },
];

export const ACCESS_SWITCH_LINKS: VlanLink[] = [
  {
    id: "link-pc1-sw1",
    sourceNodeId: "pc-1",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/1",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc2-sw1",
    sourceNodeId: "pc-2",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/2",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc3-sw1",
    sourceNodeId: "pc-3",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/3",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc4-sw1",
    sourceNodeId: "pc-4",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/4",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
];

// ─── Preset 2: Two Switches with 802.1Q Trunk ───────────────────────────────
export const TRUNKING_NODES: VlanNode[] = [
  {
    id: "pc-1",
    name: "Eng Host (Bldg 1)",
    label: "Eng-Bldg1",
    type: "host",
    ipAddress: "192.168.10.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:01",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 80, y: 100 },
  },
  {
    id: "pc-2",
    name: "Sales Host (Bldg 1)",
    label: "Sales-Bldg1",
    type: "host",
    ipAddress: "192.168.20.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:02",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 80, y: 280 },
  },
  {
    id: "sw-1",
    name: "Building 1 Switch",
    label: "SW-Bldg1",
    type: "switch",
    ipAddress: "192.168.1.251",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:01",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 230, y: 190 },
    ports: [
      {
        id: "sw1-fa0/1",
        name: "Fa0/1",
        switchId: "sw-1",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-1",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-fa0/2",
        name: "Fa0/2",
        switchId: "sw-1",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-2",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-gi0/1",
        name: "Gi0/1",
        switchId: "sw-1",
        mode: "trunk",
        pvid: 1,
        allowedVlans: [1, 10, 20, 30],
        nativeVlanId: 1,
        connectedNodeId: "sw-2",
        connectedPortName: "Gi0/1",
      },
    ],
  },
  {
    id: "sw-2",
    name: "Building 2 Switch",
    label: "SW-Bldg2",
    type: "switch",
    ipAddress: "192.168.1.252",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:02",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 410, y: 190 },
    ports: [
      {
        id: "sw2-gi0/1",
        name: "Gi0/1",
        switchId: "sw-2",
        mode: "trunk",
        pvid: 1,
        allowedVlans: [1, 10, 20, 30],
        nativeVlanId: 1,
        connectedNodeId: "sw-1",
        connectedPortName: "Gi0/1",
      },
      {
        id: "sw2-fa0/1",
        name: "Fa0/1",
        switchId: "sw-2",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-3",
        connectedPortName: "eth0",
      },
      {
        id: "sw2-fa0/2",
        name: "Fa0/2",
        switchId: "sw-2",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-4",
        connectedPortName: "eth0",
      },
    ],
  },
  {
    id: "pc-3",
    name: "Eng Host (Bldg 2)",
    label: "Eng-Bldg2",
    type: "host",
    ipAddress: "192.168.10.20",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:03",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 560, y: 100 },
  },
  {
    id: "pc-4",
    name: "Sales Host (Bldg 2)",
    label: "Sales-Bldg2",
    type: "host",
    ipAddress: "192.168.20.20",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:04",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 560, y: 280 },
  },
];

export const TRUNKING_LINKS: VlanLink[] = [
  {
    id: "link-pc1-sw1",
    sourceNodeId: "pc-1",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/1",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc2-sw1",
    sourceNodeId: "pc-2",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/2",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-sw1-sw2-trunk",
    sourceNodeId: "sw-1",
    targetNodeId: "sw-2",
    sourcePortName: "Gi0/1",
    targetPortName: "Gi0/1",
    linkType: "trunk",
    trunkAllowedVlans: [1, 10, 20, 30],
    nativeVlanId: 1,
    speedMbps: 10000,
    enabled: true,
  },
  {
    id: "link-sw2-pc3",
    sourceNodeId: "sw-2",
    targetNodeId: "pc-3",
    sourcePortName: "Fa0/1",
    targetPortName: "eth0",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-sw2-pc4",
    sourceNodeId: "sw-2",
    targetNodeId: "pc-4",
    sourcePortName: "Fa0/2",
    targetPortName: "eth0",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
];

// ─── Preset 3: Router-on-a-Stick (Inter-VLAN ROAS) ──────────────────────────
export const ROAS_NODES: VlanNode[] = [
  {
    id: "router-1",
    name: "Gateway Router (ROAS)",
    label: "Router-ROAS",
    type: "router",
    ipAddress: "192.168.1.1",
    subnetMask: "255.255.255.0",
    macAddress: "00:C0:00:AA:BB:01",
    vlanId: 1,
    position: { x: 320, y: 70 },
    subInterfaces: [
      {
        id: "r1-g0/0.10",
        name: "Gi0/0.10",
        parentPort: "Gi0/0",
        vlanId: 10,
        ipAddress: "192.168.10.1",
        subnetMask: "255.255.255.0",
        macAddress: "00:C0:00:AA:BB:10",
      },
      {
        id: "r1-g0/0.20",
        name: "Gi0/0.20",
        parentPort: "Gi0/0",
        vlanId: 20,
        ipAddress: "192.168.20.1",
        subnetMask: "255.255.255.0",
        macAddress: "00:C0:00:AA:BB:20",
      },
    ],
  },
  {
    id: "sw-1",
    name: "Core Access Switch",
    label: "SW-Core",
    type: "switch",
    ipAddress: "192.168.1.254",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:01",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 320, y: 200 },
    ports: [
      {
        id: "sw1-gi0/0",
        name: "Gi0/0",
        switchId: "sw-1",
        mode: "trunk",
        pvid: 1,
        allowedVlans: [1, 10, 20],
        nativeVlanId: 1,
        connectedNodeId: "router-1",
        connectedPortName: "Gi0/0",
      },
      {
        id: "sw1-fa0/1",
        name: "Fa0/1",
        switchId: "sw-1",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-1",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-fa0/2",
        name: "Fa0/2",
        switchId: "sw-1",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-2",
        connectedPortName: "eth0",
      },
    ],
  },
  {
    id: "pc-1",
    name: "PC 1 (VLAN 10 Engineering)",
    label: "Eng-PC1",
    type: "host",
    ipAddress: "192.168.10.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:01",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 140, y: 310 },
  },
  {
    id: "pc-2",
    name: "PC 2 (VLAN 20 Sales)",
    label: "Sales-PC2",
    type: "host",
    ipAddress: "192.168.20.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:02",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 500, y: 310 },
  },
];

export const ROAS_LINKS: VlanLink[] = [
  {
    id: "link-sw1-r1-trunk",
    sourceNodeId: "sw-1",
    targetNodeId: "router-1",
    sourcePortName: "Gi0/0",
    targetPortName: "Gi0/0",
    linkType: "trunk",
    trunkAllowedVlans: [1, 10, 20],
    nativeVlanId: 1,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc1-sw1",
    sourceNodeId: "pc-1",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/1",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc2-sw1",
    sourceNodeId: "pc-2",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/2",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
];

// ─── Preset 4: Layer 3 Multi-Layer Switch with SVIs ─────────────────────────
export const L3_SWITCH_NODES: VlanNode[] = [
  {
    id: "l3sw-1",
    name: "Layer 3 Switch (Multilayer Routing)",
    label: "L3-Switch-SVI",
    type: "layer3-switch",
    ipAddress: "192.168.1.1",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:33:44:01",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 320, y: 130 },
    sviInterfaces: [
      {
        vlanId: 10,
        name: "Vlan10",
        ipAddress: "192.168.10.1",
        subnetMask: "255.255.255.0",
        macAddress: "00:AA:00:33:44:10",
        enabled: true,
      },
      {
        vlanId: 20,
        name: "Vlan20",
        ipAddress: "192.168.20.1",
        subnetMask: "255.255.255.0",
        macAddress: "00:AA:00:33:44:20",
        enabled: true,
      },
    ],
    ports: [
      {
        id: "l3sw-fa0/1",
        name: "Fa0/1",
        switchId: "l3sw-1",
        mode: "access",
        pvid: 10,
        allowedVlans: [10],
        nativeVlanId: 1,
        connectedNodeId: "pc-1",
        connectedPortName: "eth0",
      },
      {
        id: "l3sw-fa0/2",
        name: "Fa0/2",
        switchId: "l3sw-1",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "pc-2",
        connectedPortName: "eth0",
      },
    ],
  },
  {
    id: "pc-1",
    name: "PC 1 (Engineering)",
    label: "Eng-PC1",
    type: "host",
    ipAddress: "192.168.10.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:10:00:01",
    defaultGateway: "192.168.10.1",
    vlanId: 10,
    position: { x: 150, y: 280 },
  },
  {
    id: "pc-2",
    name: "Server (Sales Database)",
    label: "Sales-DB",
    type: "server",
    ipAddress: "192.168.20.50",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:50",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 490, y: 280 },
  },
];

export const L3_SWITCH_LINKS: VlanLink[] = [
  {
    id: "link-pc1-l3sw",
    sourceNodeId: "pc-1",
    targetNodeId: "l3sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/1",
    linkType: "access",
    pvid: 10,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-pc2-l3sw",
    sourceNodeId: "pc-2",
    targetNodeId: "l3sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/2",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
];

// ─── Preset 5: VLAN Hopping Security Demonstration ──────────────────────────
export const VLAN_HOPPING_NODES: VlanNode[] = [
  {
    id: "attacker-1",
    name: "Rogue Attacker (Double Tagging)",
    label: "Attacker",
    type: "attacker",
    ipAddress: "192.168.1.50",
    subnetMask: "255.255.255.0",
    macAddress: "00:DE:AD:BE:EF:66",
    vlanId: 1, // Native VLAN on access port
    isAttacker: true,
    position: { x: 90, y: 190 },
  },
  {
    id: "sw-1",
    name: "Vulnerable Switch 1",
    label: "SW-Vuln1",
    type: "switch",
    ipAddress: "192.168.1.251",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:01",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 250, y: 190 },
    ports: [
      {
        id: "sw1-fa0/1",
        name: "Fa0/1",
        switchId: "sw-1",
        mode: "access",
        pvid: 1, // Misconfigured on Native VLAN 1
        allowedVlans: [1],
        nativeVlanId: 1,
        connectedNodeId: "attacker-1",
        connectedPortName: "eth0",
      },
      {
        id: "sw1-gi0/1",
        name: "Gi0/1",
        switchId: "sw-1",
        mode: "trunk",
        pvid: 1,
        allowedVlans: [1, 10, 20, 30],
        nativeVlanId: 1, // Default Native VLAN
        connectedNodeId: "sw-2",
        connectedPortName: "Gi0/1",
      },
    ],
  },
  {
    id: "sw-2",
    name: "Target Switch 2",
    label: "SW-Target2",
    type: "switch",
    ipAddress: "192.168.1.252",
    subnetMask: "255.255.255.0",
    macAddress: "00:AA:00:11:22:02",
    vlanId: 1,
    vlans: DEFAULT_VLANS,
    position: { x: 420, y: 190 },
    ports: [
      {
        id: "sw2-gi0/1",
        name: "Gi0/1",
        switchId: "sw-2",
        mode: "trunk",
        pvid: 1,
        allowedVlans: [1, 10, 20, 30],
        nativeVlanId: 1,
        connectedNodeId: "sw-1",
        connectedPortName: "Gi0/1",
      },
      {
        id: "sw2-fa0/1",
        name: "Fa0/1",
        switchId: "sw-2",
        mode: "access",
        pvid: 20,
        allowedVlans: [20],
        nativeVlanId: 1,
        connectedNodeId: "victim-1",
        connectedPortName: "eth0",
      },
    ],
  },
  {
    id: "victim-1",
    name: "Victim Host (VLAN 20 Sales)",
    label: "Victim-Sales",
    type: "host",
    ipAddress: "192.168.20.10",
    subnetMask: "255.255.255.0",
    macAddress: "00:1A:2B:20:00:99",
    defaultGateway: "192.168.20.1",
    vlanId: 20,
    position: { x: 570, y: 190 },
  },
];

export const VLAN_HOPPING_LINKS: VlanLink[] = [
  {
    id: "link-atk-sw1",
    sourceNodeId: "attacker-1",
    targetNodeId: "sw-1",
    sourcePortName: "eth0",
    targetPortName: "Fa0/1",
    linkType: "access",
    pvid: 1,
    speedMbps: 1000,
    enabled: true,
  },
  {
    id: "link-sw1-sw2-trunk",
    sourceNodeId: "sw-1",
    targetNodeId: "sw-2",
    sourcePortName: "Gi0/1",
    targetPortName: "Gi0/1",
    linkType: "trunk",
    trunkAllowedVlans: [1, 10, 20, 30],
    nativeVlanId: 1,
    speedMbps: 10000,
    enabled: true,
  },
  {
    id: "link-sw2-vic",
    sourceNodeId: "sw-2",
    targetNodeId: "victim-1",
    sourcePortName: "Fa0/1",
    targetPortName: "eth0",
    linkType: "access",
    pvid: 20,
    speedMbps: 1000,
    enabled: true,
  },
];

export interface VlanPresetMeta {
  id: VlanTopologyPresetId;
  name: string;
  description: string;
}

export const VLAN_PRESETS: VlanPresetMeta[] = [
  {
    id: "multi_vlan_access_switch",
    name: "Multi-VLAN Access Switch",
    description: "Single switch isolating VLAN 10 (Engineering) & VLAN 20 (Sales).",
  },
  {
    id: "two_switch_trunking",
    name: "Two Switches (802.1Q Trunk)",
    description: "Trunk link carrying multiplexed tagged frames across building switches.",
  },
  {
    id: "router_on_a_stick",
    name: "Router-on-a-Stick (ROAS)",
    description: "Inter-VLAN routing via router 802.1Q sub-interfaces (Gi0/0.10 & Gi0/0.20).",
  },
  {
    id: "layer3_switch_svi",
    name: "Layer 3 Switch (SVI Routing)",
    description: "Multilayer switch hardware wire-speed routing using Switched Virtual Interfaces.",
  },
  {
    id: "vlan_hopping_security",
    name: "VLAN Hopping Attack & Security",
    description: "Security demonstration of Double Tagging attack bypassing VLAN boundaries.",
  },
];

export interface VlanScenarioMeta {
  id: VlanScenarioId;
  name: string;
  badge: string;
  description: string;
  highlights: string[];
}

export const VLAN_SCENARIOS: VlanScenarioMeta[] = [
  {
    id: "intra_vlan_broadcast_isolation",
    name: "Intra-VLAN Broadcast Confinement",
    badge: "Layer 2 Isolation",
    description:
      "Host Eng-PC1 in VLAN 10 broadcasts an ARP request. The switch floods the broadcast frame ONLY to ports in VLAN 10. Ports in VLAN 20 receive ZERO broadcast noise.",
    highlights: [
      "Access port PVID tag association",
      "Switch CAM & VLAN filtering table",
      "Broadcast isolation preventing cross-talk",
      "Bandwidth & security containment",
    ],
  },
  {
    id: "trunk_8021q_tagging",
    name: "802.1Q Trunk Tagging & Stripping",
    badge: "IEEE 802.1Q Trunking",
    description:
      "Eng-PC1 in Bldg 1 communicates with Eng-PC2 in Bldg 2. Switch 1 injects a 4-byte 802.1Q tag (VID: 10). The tagged frame traverses the trunk. Switch 2 strips the tag before delivering to the destination access port.",
    highlights: [
      "4-byte 802.1Q header tag insertion (TPID 0x8100)",
      "12-bit VLAN ID (VID) & 3-bit Priority (PCP)",
      "Trunk port multiplexing across physical link",
      "Egress tag stripping (Untagged delivery to host)",
    ],
  },
  {
    id: "inter_vlan_router_on_a_stick",
    name: "Inter-VLAN Routing (Router-on-a-Stick)",
    badge: "Layer 3 Sub-Interfaces",
    description:
      "Eng-PC1 (VLAN 10 / 192.168.10.10) sends a packet to Sales-PC2 (VLAN 20 / 192.168.20.10). Traffic is forwarded tagged to the Router, which routes between sub-interfaces Gi0/0.10 and Gi0/0.20 and re-encapsulates it for VLAN 20.",
    highlights: [
      "Cross-subnet default gateway forwarding",
      "802.1Q sub-interfaces (Gi0/0.10 -> Gi0/0.20)",
      "Layer 2 frame rewrite (MAC decapsulation & encapsulation)",
      "Trunk hair-pinning through router interface",
    ],
  },
  {
    id: "inter_vlan_l3_svi",
    name: "Inter-VLAN Routing (Layer 3 Switch SVI)",
    badge: "Wire-Speed SVI",
    description:
      "Eng-PC1 routes to Sales-DB server through Switched Virtual Interfaces (Vlan10 & Vlan20) inside a Multi-Layer Switch with sub-microsecond hardware ASIC performance.",
    highlights: [
      "Switched Virtual Interface (SVI / interface Vlan 10)",
      "Internal hardware ASIC wire-speed packet rewrite",
      "Zero trunk bottleneck compared to ROAS",
      "Enterprise core/distribution layer architecture",
    ],
  },
  {
    id: "native_vlan_untagged",
    name: "Native VLAN Untagged Transit",
    badge: "Native VLAN (PVID 1)",
    description:
      "Frames belonging to the configured Native VLAN (VLAN 1) traverse the 802.1Q trunk link UNTAGGED without a 4-byte header, maintaining backwards compatibility with legacy hubs.",
    highlights: [
      "Untagged transmission over 802.1Q trunk",
      "Native VLAN ID mapping on receiving switch",
      "Native VLAN mismatch hazards (CDP/LLDP alerts)",
      "Security best practice (Dedicated unused Native VLAN)",
    ],
  },
  {
    id: "vlan_hopping_attack",
    name: "Double Tagging VLAN Hopping Attack",
    badge: "Security & Exploit",
    description:
      "An attacker transmits a malicious frame with TWO 802.1Q headers: Outer Tag = Native VLAN 1, Inner Tag = Target VLAN 20. Switch 1 strips the outer tag and forwards the inner-tagged frame, allowing the attacker to unilaterally penetrate VLAN 20!",
    highlights: [
      "Double 802.1Q encapsulation [Outer: 1][Inner: 20]",
      "Switch 1 strips Native tag and floods inner tag onto trunk",
      "Switch 2 delivers inner payload to victim in VLAN 20",
      "Mitigation: Explicit Native tagging or unused Native VLAN ID",
    ],
  },
];

export function getVlanPresetData(presetId: VlanTopologyPresetId): {
  nodes: VlanNode[];
  links: VlanLink[];
} {
  switch (presetId) {
    case "two_switch_trunking":
      return { nodes: TRUNKING_NODES, links: TRUNKING_LINKS };
    case "router_on_a_stick":
      return { nodes: ROAS_NODES, links: ROAS_LINKS };
    case "layer3_switch_svi":
      return { nodes: L3_SWITCH_NODES, links: L3_SWITCH_LINKS };
    case "vlan_hopping_security":
      return { nodes: VLAN_HOPPING_NODES, links: VLAN_HOPPING_LINKS };
    case "multi_vlan_access_switch":
    default:
      return { nodes: ACCESS_SWITCH_NODES, links: ACCESS_SWITCH_LINKS };
  }
}
