import type { ExplanationSection } from "@/features/protocols/shared/protocol-types";

export const OSPF_EXPLANATION_SECTIONS: ExplanationSection[] = [
  {
    eventType: "state-change",
    beginner: {
      whatHappened: "An OSPF process started or a router's neighbor state changed.",
      whyItHappened: "Routers must initialize their OSPF state machine and negotiate with neighbors to exchange routing information.",
      protocolRule: "OSPF RFC 2328 specifies a 7-state neighbor state machine (Down, Init, 2-Way, ExStart, Exchange, Loading, Full).",
      fieldsChanged: ["neighborState", "processState"],
      whatHappensNext: "The router will send or process further Hello/DBD/LSR packets to reach the Full state.",
      misconception: "Routers do not immediately exchange routing tables upon discovering a neighbor; they must first establish adjacency.",
      realWorldUse: "OSPF is widely used inside enterprise networks and data centers for automatic internal IP routing.",
    },
    advanced: {
      whatHappened: "OSPF Finite State Machine (FSM) transition occurred on an interface.",
      whyItHappened: "Event-driven transition triggered by receipt of Hello, DBD negotiation, or database synchronization completion.",
      protocolRule: "RFC 2328 Section 10.3: Interfaces transition through Down -> Init -> 2-Way -> ExStart -> Exchange -> Loading -> Full based on packet exchange criteria.",
      fieldsChanged: ["neighbor.state", "neighbor.deadTimer", "router.state"],
      whatHappensNext: "DR/BDR election proceeds in 2-Way, or Master/Slave DD sequence number exchange proceeds in ExStart.",
      misconception: "On broadcast multi-access links, non-DR/BDR routers (DROthers) stay in 2-Way state with each other rather than forming Full adjacencies.",
      realWorldUse: "Enables fast sub-second failover with BFD (Bidirectional Forwarding Detection) in tier-1 enterprise backbones.",
    },
  },
  {
    eventType: "packet-sent",
    beginner: {
      whatHappened: "An OSPF packet (Hello, DBD, LSR, LSU, or LSAck) was sent across a network link.",
      whyItHappened: "Routers communicate link-state information and maintain neighbor relationships by sending specialized OSPF packets.",
      protocolRule: "OSPF runs directly over IP (protocol number 89) without using TCP or UDP transport.",
      fieldsChanged: ["packetQueue", "txPackets"],
      whatHappensNext: "The receiving router parses the packet, updates its timers, and responds appropriately.",
      misconception: "OSPF does not use UDP or TCP; it has its own reliable transport mechanisms (LSU/LSAck).",
      realWorldUse: "Periodic Hellos ensure quick detection if a link or neighboring router goes down.",
    },
    advanced: {
      whatHappened: "OSPFv2 PDU transmitted over IPv4 using multicast (224.0.0.5 or 224.0.0.6) or unicast.",
      whyItHappened: "Periodic Hello interval timer expired or an LSA change triggered an immediate Link-State Update flood.",
      protocolRule: "RFC 2328 Section 8: OSPF packet header contains Type, Packet Length, Router ID, Area ID, Checksum, and AuType.",
      fieldsChanged: ["interface.txCount", "link.activePackets"],
      whatHappensNext: "Neighbor validates Area ID, AuType, Hello/Dead intervals, and subnet mask before processing payload.",
      misconception: "Hellos use link-local multicast with TTL=1, ensuring they do not leak beyond the direct subnet.",
      realWorldUse: "Engineers adjust Hello and Dead timers (e.g. 1s/4s) or enable BFD for mission-critical low latency convergence.",
    },
  },
  {
    eventType: "neighbor-discovered",
    beginner: {
      whatHappened: "A router received a Hello packet from a previously unknown neighbor router.",
      whyItHappened: "Hello packets are periodically sent to the multicast group 224.0.0.5 so routers dynamically discover each other without manual configuration.",
      protocolRule: "A neighbor is added to the local neighbor table in Init state when its Hello is first received.",
      fieldsChanged: ["neighborTable", "neighborCount"],
      whatHappensNext: "The router includes the new neighbor's Router ID in its next outgoing Hello packet.",
      misconception: "OSPF routers do not need manual neighbor IP configuration on broadcast/point-to-point links.",
      realWorldUse: "Zero-touch neighbor discovery simplifies scaling campus networks when new switches/routers are plugged in.",
    },
    advanced: {
      whatHappened: "New neighbor entry created in the OSPF neighbor database in Init state.",
      whyItHappened: "Incoming Hello packet contained a valid OSPF header from a new source Router ID.",
      protocolRule: "RFC 2328 Section 10.5: Neighbor structure allocated; DeadTimer initialized to DeadInterval seconds.",
      fieldsChanged: ["neighbor.id", "neighbor.state", "neighbor.ip"],
      whatHappensNext: "When the neighbor replies with a Hello listing the local Router ID, the state transitions to 2-Way.",
      misconception: "If Router IDs match between two routers, adjacency will fail and cause routing instabilities.",
      realWorldUse: "Enterprise monitoring systems track neighbor discovery events via SNMP traps and syslog alerts.",
    },
  },
  {
    eventType: "route-calculated",
    beginner: {
      whatHappened: "Dijkstra's Shortest Path First (SPF) algorithm executed to calculate the best paths.",
      whyItHappened: "All routers have synchronized their Link-State Databases (LSDB), giving every router a complete map of the network.",
      protocolRule: "Dijkstra's algorithm computes the shortest path tree from the root router to every destination subnet based on link costs.",
      fieldsChanged: ["spfTree", "calculatedRoutes"],
      whatHappensNext: "The optimal shortest paths are installed into the router's IP routing table.",
      misconception: "OSPF does not select paths based on hop count like RIP; it selects paths based on cumulative interface bandwidth/cost.",
      realWorldUse: "OSPF automatically routes traffic over 10Gbps/100Gbps links instead of slower 1Gbps backup links.",
    },
    advanced: {
      whatHappened: "Full SPF calculation run on the area Link-State Database (LSDB) directed graph.",
      whyItHappened: "Topology change detected (or initial LSDB synchronization reached) triggering SPF tree recomputation.",
      protocolRule: "RFC 2328 Section 16: Dijkstra algorithm initializes Root at distance 0, iterates candidate list, and adds lowest-cost vertex to SPT.",
      fieldsChanged: ["routingTable", "sptRoot", "nextHopTable"],
      whatHappensNext: "Routing Information Base (RIB) and Forwarding Information Base (FIB) updated with intra-area (O) routes (AD=110).",
      misconception: "SPF calculation is CPU-intensive, which is why large OSPF networks are partitioned into multiple Areas.",
      realWorldUse: "OSPF Areas (e.g. Area 0 backbone + Area 1/2) contain LSA flooding and reduce SPF calculation scope.",
    },
  },
  {
    eventType: "route-updated",
    beginner: {
      whatHappened: "The router installed the calculated shortest path routes into its routing table.",
      whyItHappened: "SPF determined the lowest cost path to reach remote networks.",
      protocolRule: "OSPF routes are assigned an Administrative Distance of 110 in standard routing tables.",
      fieldsChanged: ["routingTable", "activePath"],
      whatHappensNext: "Packets sent to destination subnets are forwarded out the selected exit interface toward the next-hop router.",
      misconception: "Routers do not forward based on the entire path; they only need to know the immediate next-hop IP and exit interface.",
      realWorldUse: "Allows packets to seamlessly navigate around network links with optimal performance.",
    },
    advanced: {
      whatHappened: "IP Routing Table (RIB) updated with next-hop IP, metric, and exit interface.",
      whyItHappened: "Shortest Path Tree resolution completed for destination prefix.",
      protocolRule: "Routes marked with source code 'O' (Intra-area), 'O IA' (Inter-area), or 'O E1/E2' (External).",
      fieldsChanged: ["routingTable.entries", "fib.forwardingTable"],
      whatHappensNext: "Data plane hardware ASIC tables updated for wire-speed line-rate forwarding.",
      misconception: "If multiple paths have identical lowest cost, OSPF performs Equal-Cost Multi-Path (ECMP) load balancing.",
      realWorldUse: "ECMP allows data center fabrics to multiply total throughput across redundant leaf-spine switches.",
    },
  },
];
