import type { LearningTopic } from "@/data/learning-content";

export const icmpTopic: LearningTopic = {
  id: "icmp",
  title: "ICMP",
  subtitle: "Internet Control Message Protocol for Network Layer error reporting and operational diagnostics (IP Protocol 1)",
  category: "services",
  readTime: "7 min",
  summary:
    "ICMP (Internet Control Message Protocol, RFC 792) is a supporting Network Layer (Layer 3) protocol used by network devices to send error messages and operational control information regarding packet delivery failures.",
  keyTakeaways: [
    "Operates at Layer 3 (Network Layer) alongside IPv4 and IPv6 (IP Protocol 1).",
    "Does NOT carry application user data; used strictly for network control and diagnostics.",
    "Categorized by Type and Code fields in the ICMP header.",
    "Powers diagnostic tools like Ping (Echo Request/Reply) and Traceroute (Time Exceeded).",
    "Firewalls often block ICMP to prevent network discovery and reconnaissance attacks.",
  ],
  diagram: {
    title: "ICMP Control Message Structure & Common Types Table",
    textRepresentation: `ICMP Encapsulation:
[ IP Header (Protocol 1) ] [ ICMP Type (1B) | ICMP Code (1B) | Checksum (2B) | Payload Data ]

Common ICMP Message Types Table:
+-----------+-----------+--------------------------+----------------------------------------------+
| Type Code | Name      | Meaning                  | Trigger / Usage                              |
+-----------+-----------+--------------------------+----------------------------------------------+
| Type 8    | Echo Req  | Ping Request             | Generated by ping utility                    |
| Type 0    | Echo Rep  | Ping Reply               | Responded by destination host                |
| Type 3    | Unreach   | Destination Unreachable  | Router cannot forward to target IP/Port      |
| Type 11   | Time Excd | Time Exceeded (TTL=0)    | Router drops packet whose TTL reached 0      |
+-----------+-----------+--------------------------+----------------------------------------------+`,
  },
  importantTerms: [
    { term: "ICMP Type", definition: "An 8-bit field specifying the general message category (e.g. Type 3 = Destination Unreachable)." },
    { term: "ICMP Code", definition: "An 8-bit field providing specific details within a Type category (e.g. Type 3 Code 3 = Port Unreachable)." },
    { term: "Destination Unreachable", definition: "Message generated by a router or host when a packet cannot be delivered due to link, route, or port failure." },
    { term: "Time Exceeded (TTL Expired)", definition: "Message generated by a router when a packet's TTL drops to zero, used by Traceroute." },
    { term: "Redirect", definition: "Message sent by a router informing a host of a better next-hop router on the local link." },
  ],
  sections: [
    {
      id: "why-icmp-needed",
      title: "Why ICMP is Needed",
      body: "IP is an unacknowledged best-effort protocol. If a router encounters a broken link, a full queue, or a non-existent IP address, IP itself has no mechanism to notify the sender. ICMP provides error feedback.",
    },
    {
      id: "how-icmp-works-traceroute",
      title: "How Traceroute Uses ICMP",
      body: "The Traceroute utility leverages ICMP Time Exceeded (Type 11) messages to map hop-by-hop router paths:",
      bullets: [
        "1. Sends first packet with TTL=1. Router 1 decrements TTL to 0, drops packet, and returns ICMP Type 11 (discovering Hop 1 IP).",
        "2. Sends second packet with TTL=2. Router 2 drops packet at TTL 0 and returns ICMP Type 11 (discovering Hop 2 IP).",
        "3. Increments TTL sequentially until destination returns ICMP Echo Reply or Port Unreachable.",
      ],
    },
    {
      id: "why-firewalls-block-icmp",
      title: "Why Firewalls Block ICMP",
      body: "Security teams frequently block inbound ICMP at network perimeter firewalls because attackers use ICMP pings and sweeps to discover active host IP addresses and map internal network topologies.",
    },
  ],
  advantages: [
    "Essential for network diagnostics, latency measurement, and MTU Path Discovery.",
    "Lightweight control protocol built into every standard IP stack.",
  ],
  disadvantages: [
    "Can be abused for denial-of-service attacks (e.g. ICMP Flood / Smurf Attack).",
    "Indiscriminate ICMP blocking by network administrators breaks useful diagnostics and Path MTU Discovery.",
  ],
  commonUseCases: [
    "Pinging devices to check up/down status.",
    "Running Traceroute to pinpoint network bottleneck hops.",
    "Path MTU Discovery (PMTUD) to prevent packet fragmentation.",
  ],
  commonMistakes: [
    "Confusing ICMP with transport protocols like TCP or UDP — ICMP operates alongside IP at Layer 3 and does not use TCP/UDP port numbers.",
    "Assuming ICMP guarantees delivery — ICMP reports errors, but does not retransmit lost packets.",
  ],
  comparison: {
    headers: ["Aspect", "ICMP", "TCP / UDP"],
    rows: [
      { label: "OSI Layer", classful: "Layer 3 (Network Layer Control)", cidr: "Layer 4 (Transport Layer Data)" },
      { label: "Ports Used", classful: "No port numbers (Type & Code instead)", cidr: "16-bit Source & Destination Ports (0-65535)" },
      { label: "Purpose", classful: "Network error feedback & diagnostics", cidr: "Application data delivery between software processes" },
    ],
  },
  beginnerSummary:
    "ICMP is the network's automated feedback system. When a packet runs into a dead-end road, a blocked port, or a expired timer, ICMP generates a message back to the sender explaining what went wrong.",
  relatedLinks: [
    { label: "Ping", href: "/learn/ping" },
    { label: "IP Address", href: "/learn/ip-address" },
    { label: "TCP", href: "/learn/tcp" },
    { label: "UDP", href: "/learn/udp" },
  ],
};
