import type { LearningTopic } from "@/data/learning-content";

export const pingTopic: LearningTopic = {
  id: "ping",
  title: "Ping",
  subtitle: "Command-line diagnostic utility for testing host reachability and Round-Trip Time (RTT)",
  category: "services",
  readTime: "6 min",
  summary:
    "Ping is a network diagnostic utility used to test whether a specific destination host is reachable across an IP network. It operates by sending ICMP Echo Request packets to the target and waiting for ICMP Echo Reply responses.",
  keyTakeaways: [
    "Ping is a diagnostic utility software command, NOT a standalone transport protocol.",
    "Uses ICMP (Internet Control Message Protocol) Echo Request and Echo Reply messages.",
    "Measures Round-Trip Time (RTT) in milliseconds (ms) and calculates packet loss percentage.",
    "Can test targets using either an IP address or a hostname.",
    "A successful ping proves Layer 3 reachability, but a failed ping does NOT automatically mean a service is down (firewalls often block ICMP).",
  ],
  diagram: {
    title: "Ping Request/Reply Operation & CLI Example",
    textRepresentation: `Ping Exchange:
Source (PC-1) ─── ICMP Echo Request (Type 8) ───► Target (Server)
Source (PC-1) ◄─── ICMP Echo Reply (Type 0) ──── Target (Server)

Command CLI Example:
$ ping 192.168.1.20

Output:
Pinging 192.168.1.20 with 32 bytes of data:
Reply from 192.168.1.20: bytes=32 time=2ms TTL=64
Reply from 192.168.1.20: bytes=32 time=1ms TTL=64
--- 192.168.1.20 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, rtt min/avg/max = 1/1.5/2 ms`,
  },
  importantTerms: [
    { term: "Round-Trip Time (RTT)", definition: "The total elapsed time in milliseconds for a ping packet to travel to the destination and back." },
    { term: "Packet Loss", definition: "The percentage of transmitted ping requests that fail to receive a reply." },
    { term: "ICMP Echo Request", definition: "ICMP Type 8 message generated by ping to request a response." },
    { term: "ICMP Echo Reply", definition: "ICMP Type 0 message returned by the destination host upon receiving a request." },
    { term: "Destination Host Unreachable", definition: "Error message indicating local router cannot resolve ARP or route to destination." },
    { term: "Request Timed Out", definition: "Indicates the ping packet was sent but no reply was received before the timeout limit." },
  ],
  sections: [
    {
      id: "why-ping-needed",
      title: "Why Ping is Needed",
      body: "Network engineers and end users use ping as the very first step in bottom-up troubleshooting. It rapidly verifies basic Layer 1 through Layer 3 IP connectivity between two devices on a local subnet or across the Internet.",
    },
    {
      id: "how-ping-works",
      title: "How Ping Works: IP vs Hostname",
      body: "Ping can be executed against an IP address or a domain hostname:",
      bullets: [
        "Pinging IP (ping 192.168.1.1): Directly transmits ICMP Echo Request to the IP.",
        "Pinging Hostname (ping example.com): Client first invokes DNS to resolve example.com to an IP address, then transmits ICMP Echo Requests to that resolved IP.",
      ],
    },
    {
      id: "ping-failure-causes",
      title: "Why Ping Can Fail",
      body: "A failed ping response can be caused by several distinct network issues:",
      bullets: [
        "Firewall Blocking: Host or network firewalls frequently block ICMP Echo Requests for security.",
        "Wrong Gateway / Route: Missing return routes on target servers.",
        "Physical Link Down: Unplugged cables or inactive Wi-Fi connections.",
        "DNS Failure: If pinging by hostname, DNS resolution failure prevents ping from initiating.",
      ],
    },
  ],
  advantages: [
    "Installed natively on virtually every operating system (Windows, macOS, Linux, Cisco IOS).",
    "Provides immediate feedback on network latency and packet drops.",
    "Simple syntax requiring no special software installation.",
  ],
  disadvantages: [
    "Frequently blocked by corporate firewalls, causing false-negative test results.",
    "Proves Layer 3 reachability only — does NOT verify whether Layer 7 web servers (Port 80/443) or database ports are accepting connections.",
  ],
  commonUseCases: [
    "Verifying default gateway reachability during initial PC setup.",
    "Checking network latency and packet loss to gaming or DNS servers.",
  ],
  commonMistakes: [
    "Calling Ping a protocol — Ping is a command utility tool; ICMP is the protocol it uses.",
    "Assuming a server is offline just because it doesn't respond to ping — many servers drop ping requests but serve web pages normally.",
  ],
  comparison: {
    headers: ["Aspect", "Ping Tool", "ICMP Protocol"],
    rows: [
      { label: "Definition", classful: "User diagnostic software CLI executable", cidr: "Network Layer control & error protocol" },
      { label: "Function", classful: "Sends request, measures RTT and loss", cidr: "Defines packet header structure & message types" },
      { label: "Messages Used", classful: "Echo Request (Type 8), Echo Reply (Type 0)", cidr: "Echo, Unreachable, Time Exceeded, Redirects" },
    ],
  },
  beginnerSummary:
    "Ping is a diagnostic command that acts like calling out 'Hello!' across a network. It sends a tiny test message to a target IP address and measures how many milliseconds it takes to receive a reply.",
  relatedLinks: [
    { label: "ICMP", href: "/learn/icmp" },
    { label: "DNS", href: "/learn/dns" },
    { label: "IP Address", href: "/learn/ip-address" },
  ],
};
