import type {
  MplsConfig,
  MplsNode,
  MplsLink,
  MplsScenarioId,
  MplsTopologyPresetId,
} from "./mpls.types";

export const defaultMplsConfig: MplsConfig = {
  topologyPreset: "standard_core_lsp",
  scenarioId: "basic_push_swap_pop",
  sourceNodeId: "ce-1",
  targetNodeId: "ce-2",
  phpEnabled: true,
  ttlMode: "uniform",
  trafficClassExp: 0, // 0 = Best Effort (DSCP 000000)
  stackDepth: "single",
  simulateLinkFailure: false,
  customerVrf: "GLOBAL_IP",
};

// ==========================================
// TOPOLOGY 1: Standard Core LSP (5-Router)
// CE1 (10.1.1.2) -> PE1 (10.0.1.1) -> P1 (10.0.2.1) -> P2 (10.0.3.1) -> PE2 (10.0.4.2) -> CE2 (10.2.2.2)
// ==========================================
export const STANDARD_CORE_NODES: MplsNode[] = [
  {
    id: "ce-1",
    name: "Customer Edge 1",
    label: "CE-1 (Site 1)",
    role: "ce",
    ipAddress: "10.1.1.2",
    loopbackIp: "10.1.1.2",
    routerId: "10.1.1.2",
    position: { x: 80, y: 220 },
    activeLabels: [],
    status: "active",
    fib: [
      { prefix: "10.2.2.0/24", nextHop: "10.1.1.1", outInterface: "Gi0/0", action: "FORWARD_IP" },
      { prefix: "0.0.0.0/0", nextHop: "10.1.1.1", outInterface: "Gi0/0", action: "FORWARD_IP" },
    ],
    lib: [],
    lfib: [],
  },
  {
    id: "pe-1",
    name: "Ingress Provider Edge 1",
    label: "PE-1 (Ingress LER)",
    role: "ingress-ler",
    ipAddress: "10.1.1.1",
    loopbackIp: "1.1.1.1",
    routerId: "1.1.1.1",
    asn: 65000,
    position: { x: 260, y: 220 },
    activeLabels: [101],
    status: "active",
    fib: [
      { prefix: "10.2.2.0/24", nextHop: "10.0.1.2", outInterface: "Gi0/1", action: "PUSH", pushLabels: [101] },
      { prefix: "4.4.4.4/32", nextHop: "10.0.1.2", outInterface: "Gi0/1", action: "PUSH", pushLabels: [101] },
      { prefix: "10.1.1.0/24", nextHop: "Direct", outInterface: "Gi0/0", action: "FORWARD_IP" },
    ],
    lib: [
      {
        prefix: "10.2.2.0/24",
        localLabel: 101,
        remoteBindings: [{ neighborRouterId: "2.2.2.2", neighborLabel: 201 }],
      },
    ],
    lfib: [
      {
        inLabel: 101,
        outLabel: 201,
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/0",
        outInterface: "Gi0/1",
        nextHop: "10.0.1.2 (P-1)",
        action: "SWAP",
        bytesSwapped: 14200,
      },
    ],
  },
  {
    id: "p-1",
    name: "Core Provider Router 1",
    label: "P-1 (Core LSR)",
    role: "core-lsr",
    ipAddress: "10.0.1.2",
    loopbackIp: "2.2.2.2",
    routerId: "2.2.2.2",
    asn: 65000,
    position: { x: 440, y: 220 },
    activeLabels: [201],
    status: "active",
    fib: [
      { prefix: "10.2.2.0/24", nextHop: "10.0.2.2", outInterface: "Gi0/2", action: "PUSH", pushLabels: [201] },
    ],
    lib: [
      {
        prefix: "10.2.2.0/24",
        localLabel: 201,
        remoteBindings: [
          { neighborRouterId: "1.1.1.1", neighborLabel: 101 },
          { neighborRouterId: "3.3.3.3", neighborLabel: 301 },
        ],
      },
    ],
    lfib: [
      {
        inLabel: 101,
        outLabel: 201,
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.2.2 (P-2)",
        action: "SWAP",
        bytesSwapped: 84900,
      },
      {
        inLabel: 201,
        outLabel: 301,
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.2.2 (P-2)",
        action: "SWAP",
        bytesSwapped: 91400,
      },
    ],
  },
  {
    id: "p-2",
    name: "Core Provider Router 2",
    label: "P-2 (Penultimate LSR)",
    role: "penultimate-lsr",
    ipAddress: "10.0.2.2",
    loopbackIp: "3.3.3.3",
    routerId: "3.3.3.3",
    asn: 65000,
    position: { x: 620, y: 220 },
    activeLabels: [301],
    status: "active",
    fib: [
      { prefix: "10.2.2.0/24", nextHop: "10.0.3.2", outInterface: "Gi0/2", action: "PUSH", pushLabels: [301] },
    ],
    lib: [
      {
        prefix: "10.2.2.0/24",
        localLabel: 301,
        remoteBindings: [
          { neighborRouterId: "2.2.2.2", neighborLabel: 201 },
          { neighborRouterId: "4.4.4.4", neighborLabel: 3 }, // Implicit Null
        ],
      },
    ],
    lfib: [
      {
        inLabel: 201,
        outLabel: "IMPLICIT_NULL",
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.3.2 (PE-2)",
        action: "PHP",
        bytesSwapped: 73200,
      },
      {
        inLabel: 301,
        outLabel: "POP",
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.3.2 (PE-2)",
        action: "POP",
        bytesSwapped: 64100,
      },
    ],
  },
  {
    id: "pe-2",
    name: "Egress Provider Edge 2",
    label: "PE-2 (Egress LER)",
    role: "egress-ler",
    ipAddress: "10.0.3.2",
    loopbackIp: "4.4.4.4",
    routerId: "4.4.4.4",
    asn: 65000,
    position: { x: 800, y: 220 },
    activeLabels: [3],
    phpEnabled: true,
    status: "active",
    fib: [
      { prefix: "10.2.2.0/24", nextHop: "10.0.4.2", outInterface: "Gi0/1", action: "FORWARD_IP" },
    ],
    lib: [
      {
        prefix: "10.2.2.0/24",
        localLabel: 3, // Implicit Null
        remoteBindings: [{ neighborRouterId: "3.3.3.3", neighborLabel: 301 }],
      },
    ],
    lfib: [
      {
        inLabel: 301,
        outLabel: "POP",
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/0",
        outInterface: "Gi0/1",
        nextHop: "10.0.4.2 (CE-2)",
        action: "POP",
        bytesSwapped: 52000,
      },
    ],
  },
  {
    id: "ce-2",
    name: "Customer Edge 2",
    label: "CE-2 (Site 2)",
    role: "ce",
    ipAddress: "10.2.2.2",
    loopbackIp: "10.2.2.2",
    routerId: "10.2.2.2",
    position: { x: 980, y: 220 },
    activeLabels: [],
    status: "active",
    fib: [
      { prefix: "10.1.1.0/24", nextHop: "10.0.4.1", outInterface: "Gi0/0", action: "FORWARD_IP" },
      { prefix: "0.0.0.0/0", nextHop: "10.0.4.1", outInterface: "Gi0/0", action: "FORWARD_IP" },
    ],
    lib: [],
    lfib: [],
  },
];

export const STANDARD_CORE_LINKS: MplsLink[] = [
  {
    id: "link-ce1-pe1",
    sourceNodeId: "ce-1",
    targetNodeId: "pe-1",
    sourcePortName: "Gi0/0",
    targetPortName: "Gi0/0",
    bandwidthMbps: 1000,
    metric: 1,
    isLsp: false,
    status: "up",
  },
  {
    id: "link-pe1-p1",
    sourceNodeId: "pe-1",
    targetNodeId: "p-1",
    sourcePortName: "Gi0/1",
    targetPortName: "Gi0/1",
    bandwidthMbps: 10000,
    metric: 10,
    isLsp: true,
    activeLabel: 101,
    status: "up",
  },
  {
    id: "link-p1-p2",
    sourceNodeId: "p-1",
    targetNodeId: "p-2",
    sourcePortName: "Gi0/2",
    targetPortName: "Gi0/1",
    bandwidthMbps: 10000,
    metric: 10,
    isLsp: true,
    activeLabel: 201,
    status: "up",
  },
  {
    id: "link-p2-pe2",
    sourceNodeId: "p-2",
    targetNodeId: "pe-2",
    sourcePortName: "Gi0/2",
    targetPortName: "Gi0/0",
    bandwidthMbps: 10000,
    metric: 10,
    isLsp: true,
    activeLabel: 301,
    status: "up",
  },
  {
    id: "link-pe2-ce2",
    sourceNodeId: "pe-2",
    targetNodeId: "ce-2",
    sourcePortName: "Gi0/1",
    targetPortName: "Gi0/0",
    bandwidthMbps: 1000,
    metric: 1,
    isLsp: false,
    status: "up",
  },
];

// ==========================================
// TOPOLOGY 2: L3VPN Multi-Tenant (Two-Label Stack)
// ==========================================
export const L3VPN_NODES: MplsNode[] = [
  {
    id: "ce-red-1",
    name: "Customer Red Site 1",
    label: "CE-Red (Acme Corp)",
    role: "ce",
    ipAddress: "192.168.1.2",
    loopbackIp: "192.168.1.2",
    routerId: "192.168.1.2",
    position: { x: 80, y: 120 },
    activeLabels: [],
    status: "active",
    fib: [{ prefix: "192.168.2.0/24", nextHop: "192.168.1.1", outInterface: "Gi0/0", action: "FORWARD_IP" }],
    lib: [],
    lfib: [],
  },
  {
    id: "ce-blue-1",
    name: "Customer Blue Site 1",
    label: "CE-Blue (Globex Corp)",
    role: "ce",
    ipAddress: "192.168.1.2", // Overlapping IP space allowed due to VRF!
    loopbackIp: "192.168.1.2",
    routerId: "192.168.1.2",
    position: { x: 80, y: 320 },
    activeLabels: [],
    status: "active",
    fib: [{ prefix: "192.168.2.0/24", nextHop: "192.168.1.1", outInterface: "Gi0/0", action: "FORWARD_IP" }],
    lib: [],
    lfib: [],
  },
  {
    id: "pe-1",
    name: "Ingress Provider Edge 1",
    label: "PE-1 (L3VPN Ingress)",
    role: "ingress-ler",
    ipAddress: "10.0.1.1",
    loopbackIp: "1.1.1.1",
    routerId: "1.1.1.1",
    asn: 65000,
    position: { x: 280, y: 220 },
    activeLabels: [101, 501, 502],
    status: "active",
    vrfs: [
      {
        vrfName: "VRF_RED_CUSTOMER_A",
        routeDistinguisher: "65000:10",
        routeTargetExport: "65000:10",
        routeTargetImport: "65000:10",
        vpnLabel: 501,
        routes: [{ prefix: "192.168.2.0/24", nextHop: "4.4.4.4", interface: "Gi0/1" }],
      },
      {
        vrfName: "VRF_BLUE_CUSTOMER_B",
        routeDistinguisher: "65000:20",
        routeTargetExport: "65000:20",
        routeTargetImport: "65000:20",
        vpnLabel: 502,
        routes: [{ prefix: "192.168.2.0/24", nextHop: "4.4.4.4", interface: "Gi0/1" }],
      },
    ],
    fib: [
      { prefix: "4.4.4.4/32", nextHop: "10.0.1.2", outInterface: "Gi0/1", action: "PUSH", pushLabels: [101] },
    ],
    lib: [
      { prefix: "4.4.4.4/32", localLabel: 101, remoteBindings: [{ neighborRouterId: "2.2.2.2", neighborLabel: 201 }] },
    ],
    lfib: [
      {
        inLabel: 101,
        outLabel: 201,
        prefix: "4.4.4.4/32",
        inInterface: "Gi0/0",
        outInterface: "Gi0/1",
        nextHop: "10.0.1.2 (P-1)",
        action: "SWAP",
        bytesSwapped: 128000,
      },
    ],
  },
  {
    id: "p-1",
    name: "Core Provider Router 1",
    label: "P-1 (Core LSR)",
    role: "core-lsr",
    ipAddress: "10.0.1.2",
    loopbackIp: "2.2.2.2",
    routerId: "2.2.2.2",
    asn: 65000,
    position: { x: 460, y: 220 },
    activeLabels: [201],
    status: "active",
    fib: [{ prefix: "4.4.4.4/32", nextHop: "10.0.2.2", outInterface: "Gi0/2", action: "PUSH", pushLabels: [201] }],
    lib: [{ prefix: "4.4.4.4/32", localLabel: 201, remoteBindings: [{ neighborRouterId: "3.3.3.3", neighborLabel: 301 }] }],
    lfib: [
      {
        inLabel: 101,
        outLabel: 201,
        prefix: "4.4.4.4/32",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.2.2 (P-2)",
        action: "SWAP",
        bytesSwapped: 340000,
      },
    ],
  },
  {
    id: "p-2",
    name: "Core Provider Router 2",
    label: "P-2 (PHP LSR)",
    role: "penultimate-lsr",
    ipAddress: "10.0.2.2",
    loopbackIp: "3.3.3.3",
    routerId: "3.3.3.3",
    asn: 65000,
    position: { x: 640, y: 220 },
    activeLabels: [301],
    status: "active",
    fib: [{ prefix: "4.4.4.4/32", nextHop: "10.0.3.2", outInterface: "Gi0/2", action: "PUSH", pushLabels: [301] }],
    lib: [{ prefix: "4.4.4.4/32", localLabel: 301, remoteBindings: [{ neighborRouterId: "4.4.4.4", neighborLabel: 3 }] }],
    lfib: [
      {
        inLabel: 201,
        outLabel: "IMPLICIT_NULL",
        prefix: "4.4.4.4/32",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.3.2 (PE-2)",
        action: "PHP",
        bytesSwapped: 290000,
      },
    ],
  },
  {
    id: "pe-2",
    name: "Egress Provider Edge 2",
    label: "PE-2 (L3VPN Egress)",
    role: "egress-ler",
    ipAddress: "10.0.3.2",
    loopbackIp: "4.4.4.4",
    routerId: "4.4.4.4",
    asn: 65000,
    position: { x: 820, y: 220 },
    activeLabels: [501, 502],
    status: "active",
    vrfs: [
      {
        vrfName: "VRF_RED_CUSTOMER_A",
        routeDistinguisher: "65000:10",
        routeTargetExport: "65000:10",
        routeTargetImport: "65000:10",
        vpnLabel: 501,
        routes: [{ prefix: "192.168.2.0/24", nextHop: "192.168.2.2", interface: "Gi0/1" }],
      },
      {
        vrfName: "VRF_BLUE_CUSTOMER_B",
        routeDistinguisher: "65000:20",
        routeTargetExport: "65000:20",
        routeTargetImport: "65000:20",
        vpnLabel: 502,
        routes: [{ prefix: "192.168.2.0/24", nextHop: "192.168.2.2", interface: "Gi0/2" }],
      },
    ],
    fib: [
      { prefix: "192.168.2.0/24", nextHop: "192.168.2.2", outInterface: "Gi0/1", action: "FORWARD_IP" },
    ],
    lib: [],
    lfib: [
      {
        inLabel: 501,
        outLabel: "POP",
        prefix: "VRF_RED: 192.168.2.0/24",
        inInterface: "Gi0/0",
        outInterface: "Gi0/1",
        nextHop: "192.168.2.2 (CE-Red-2)",
        action: "POP",
        bytesSwapped: 154000,
      },
      {
        inLabel: 502,
        outLabel: "POP",
        prefix: "VRF_BLUE: 192.168.2.0/24",
        inInterface: "Gi0/0",
        outInterface: "Gi0/2",
        nextHop: "192.168.2.2 (CE-Blue-2)",
        action: "POP",
        bytesSwapped: 136000,
      },
    ],
  },
  {
    id: "ce-red-2",
    name: "Customer Red Site 2",
    label: "CE-Red (Acme Corp)",
    role: "ce",
    ipAddress: "192.168.2.2",
    loopbackIp: "192.168.2.2",
    routerId: "192.168.2.2",
    position: { x: 1020, y: 120 },
    activeLabels: [],
    status: "active",
    fib: [{ prefix: "192.168.1.0/24", nextHop: "192.168.2.1", outInterface: "Gi0/0", action: "FORWARD_IP" }],
    lib: [],
    lfib: [],
  },
  {
    id: "ce-blue-2",
    name: "Customer Blue Site 2",
    label: "CE-Blue (Globex Corp)",
    role: "ce",
    ipAddress: "192.168.2.2",
    loopbackIp: "192.168.2.2",
    routerId: "192.168.2.2",
    position: { x: 1020, y: 320 },
    activeLabels: [],
    status: "active",
    fib: [{ prefix: "192.168.1.0/24", nextHop: "192.168.2.1", outInterface: "Gi0/0", action: "FORWARD_IP" }],
    lib: [],
    lfib: [],
  },
];

export const L3VPN_LINKS: MplsLink[] = [
  { id: "link-ce-red1-pe1", sourceNodeId: "ce-red-1", targetNodeId: "pe-1", sourcePortName: "Gi0/0", targetPortName: "Gi0/2", bandwidthMbps: 1000, metric: 1, isLsp: false, status: "up" },
  { id: "link-ce-blue1-pe1", sourceNodeId: "ce-blue-1", targetNodeId: "pe-1", sourcePortName: "Gi0/0", targetPortName: "Gi0/3", bandwidthMbps: 1000, metric: 1, isLsp: false, status: "up" },
  { id: "link-pe1-p1", sourceNodeId: "pe-1", targetNodeId: "p-1", sourcePortName: "Gi0/1", targetPortName: "Gi0/1", bandwidthMbps: 10000, metric: 10, isLsp: true, activeLabel: 101, status: "up" },
  { id: "link-p1-p2", sourceNodeId: "p-1", targetNodeId: "p-2", sourcePortName: "Gi0/2", targetPortName: "Gi0/1", bandwidthMbps: 10000, metric: 10, isLsp: true, activeLabel: 201, status: "up" },
  { id: "link-p2-pe2", sourceNodeId: "p-2", targetNodeId: "pe-2", sourcePortName: "Gi0/2", targetPortName: "Gi0/0", bandwidthMbps: 10000, metric: 10, isLsp: true, activeLabel: 301, status: "up" },
  { id: "link-pe2-ce-red2", sourceNodeId: "pe-2", targetNodeId: "ce-red-2", sourcePortName: "Gi0/1", targetPortName: "Gi0/0", bandwidthMbps: 1000, metric: 1, isLsp: false, status: "up" },
  { id: "link-pe2-ce-blue2", sourceNodeId: "pe-2", targetNodeId: "ce-blue-2", sourcePortName: "Gi0/2", targetPortName: "Gi0/0", bandwidthMbps: 1000, metric: 1, isLsp: false, status: "up" },
];

// ==========================================
// TOPOLOGY 3: Fast Reroute (FRR) with Backup Bypass LSR P3
// ==========================================
export const FRR_NODES: MplsNode[] = [
  ...STANDARD_CORE_NODES.slice(0, 2),
  {
    ...STANDARD_CORE_NODES[2],
    position: { x: 440, y: 160 },
  },
  {
    id: "p-3-backup",
    name: "Backup Bypass Router",
    label: "P-3 (FRR Bypass LSR)",
    role: "backup-lsr",
    ipAddress: "10.0.9.1",
    loopbackIp: "5.5.5.5",
    routerId: "5.5.5.5",
    asn: 65000,
    position: { x: 530, y: 320 },
    activeLabels: [901],
    status: "active",
    fib: [{ prefix: "10.2.2.0/24", nextHop: "10.0.8.2", outInterface: "Gi0/2", action: "PUSH", pushLabels: [901] }],
    lib: [{ prefix: "10.2.2.0/24", localLabel: 901, remoteBindings: [{ neighborRouterId: "3.3.3.3", neighborLabel: 201 }] }],
    lfib: [
      {
        inLabel: 901,
        outLabel: 201,
        prefix: "10.2.2.0/24",
        inInterface: "Gi0/1",
        outInterface: "Gi0/2",
        nextHop: "10.0.8.2 (P-2)",
        action: "SWAP",
        bytesSwapped: 21000,
      },
    ],
  },
  {
    ...STANDARD_CORE_NODES[3],
    position: { x: 620, y: 160 },
  },
  ...STANDARD_CORE_NODES.slice(4),
];

export const FRR_LINKS: MplsLink[] = [
  STANDARD_CORE_LINKS[0],
  STANDARD_CORE_LINKS[1],
  STANDARD_CORE_LINKS[2],
  {
    id: "link-pe1-p3",
    sourceNodeId: "pe-1",
    targetNodeId: "p-3-backup",
    sourcePortName: "Gi0/2",
    targetPortName: "Gi0/1",
    bandwidthMbps: 10000,
    metric: 30,
    isLsp: true,
    isBypassLsp: true,
    activeLabel: 901,
    status: "up",
  },
  {
    id: "link-p3-p2",
    sourceNodeId: "p-3-backup",
    targetNodeId: "p-2",
    sourcePortName: "Gi0/2",
    targetPortName: "Gi0/3",
    bandwidthMbps: 10000,
    metric: 30,
    isLsp: true,
    isBypassLsp: true,
    activeLabel: 201,
    status: "up",
  },
  STANDARD_CORE_LINKS[3],
  STANDARD_CORE_LINKS[4],
];

// Presets mapping
export const MPLS_PRESETS: Record<
  MplsTopologyPresetId,
  { name: string; description: string; nodes: MplsNode[]; links: MplsLink[] }
> = {
  standard_core_lsp: {
    name: "Standard 5-Router Core LSP",
    description: "Classic MPLS network with Ingress LER PUSH, Core LSR SWAP, and Egress LER POP operations.",
    nodes: STANDARD_CORE_NODES,
    links: STANDARD_CORE_LINKS,
  },
  penultimate_hop_popping: {
    name: "Penultimate Hop Popping (PHP)",
    description: "Egress LER advertises Implicit Null (Label 3). The penultimate router strips the outer label to eliminate double lookup at egress.",
    nodes: STANDARD_CORE_NODES,
    links: STANDARD_CORE_LINKS,
  },
  l3vpn_two_label_stack: {
    name: "BGP/MPLS L3VPN (2-Label Stack)",
    description: "Multi-tenant VPN using 2 stacked labels: Outer LDP Transport Label + Inner MP-BGP VPN Label with VRF routing tables.",
    nodes: L3VPN_NODES,
    links: L3VPN_LINKS,
  },
  mpls_fast_reroute_frr: {
    name: "MPLS-TE Fast Reroute (FRR)",
    description: "Pre-computed 50ms bypass detour tunnel with label stack imposition upon primary link failure.",
    nodes: FRR_NODES,
    links: FRR_LINKS,
  },
  ttl_uniform_vs_pipe: {
    name: "TTL Uniform vs Pipe Mode",
    description: "Compare how customer traceroute sees the MPLS core when TTL is copied (Uniform) vs encapsulated (Pipe mode).",
    nodes: STANDARD_CORE_NODES,
    links: STANDARD_CORE_LINKS,
  },
};

export const MPLS_SCENARIOS: Record<
  MplsScenarioId,
  {
    title: string;
    summary: string;
    category: "LSP Operations" | "Optimization" | "VPN" | "Resilience" | "Diagnostics";
    presetId: MplsTopologyPresetId;
    learningPoints: string[];
  }
> = {
  basic_push_swap_pop: {
    title: "Basic LSP: Push, Swap, Pop",
    summary: "Simulate a packet traversing an established LSP: Ingress PE imposes label 101, Core P1 swaps 101->201, P2 swaps 201->301, PE2 pops label 301.",
    category: "LSP Operations",
    presetId: "standard_core_lsp",
    learningPoints: [
      "FEC classification occurs once at the Ingress LER.",
      "Core LSRs switch frames in hardware using fast indexed LFIB lookups without IP longest prefix matching.",
      "Label stack Bottom of Stack (S-bit) is set to 1 for single-label packets.",
    ],
  },
  php_implicit_null: {
    title: "Penultimate Hop Popping (PHP - Label 3)",
    summary: "Observe how PE2 signals Implicit Null (Label 3) via LDP. Router P-2 pops the outer label before forwarding to PE2.",
    category: "Optimization",
    presetId: "penultimate_hop_popping",
    learningPoints: [
      "Penultimate Hop Popping offloads the Egress PE from performing a double lookup (MPLS LFIB + IP FIB).",
      "Implicit Null is signaled as Label 3 in LDP and never actually appears on the physical wire.",
      "The penultimate router sends native IPv4 directly to the egress PE.",
    ],
  },
  l3vpn_multi_tenant_traffic: {
    title: "L3VPN: Two-Label Multi-Tenant Isolation",
    summary: "Two distinct customers (Acme Corp & Globex Corp) share the same IP space (192.168.1.0/24) without conflict via VRFs and 2-Label Stacking.",
    category: "VPN",
    presetId: "l3vpn_two_label_stack",
    learningPoints: [
      "Top Label (Transport): Directs packet across the core P-routers to Egress PE.",
      "Bottom Label (VPN / S=1): Directs Egress PE to inject the packet into the correct customer VRF.",
      "Core P-routers never inspect or need routes for customer IP prefixes (BGP Free Core).",
    ],
  },
  frr_link_failure_detour: {
    title: "Fast Reroute (FRR) 50ms Link Protection",
    summary: "Simulate a fiber cut on primary link PE1-P1. PE1 immediately imposes a bypass label (901) and detours traffic via backup router P3 in <50ms.",
    category: "Resilience",
    presetId: "mpls_fast_reroute_frr",
    learningPoints: [
      "FRR provides carrier-grade sub-50ms protection against link failures.",
      "Traffic is redirected without waiting for global IGP/LDP reconvergence.",
      "A 2nd outer bypass label is pushed at the Point of Local Repair (PLR).",
    ],
  },
  traceroute_uniform_mode: {
    title: "Customer Traceroute: Uniform TTL Mode",
    summary: "IP TTL is decremented and synchronized into MPLS TTL at every core hop. Customer traceroute exposes all internal P-routers.",
    category: "Diagnostics",
    presetId: "ttl_uniform_vs_pipe",
    learningPoints: [
      "Uniform mode copies IP TTL into the MPLS shim header upon ingress.",
      "When MPLS TTL expires, Core P-routers generate ICMP TTL Exceeded back to the customer.",
      "Useful for internal service provider network diagnostics.",
    ],
  },
  traceroute_pipe_mode: {
    title: "Customer Traceroute: Pipe TTL Mode",
    summary: "IP TTL is preserved and decremented by only 1 across the entire MPLS domain. The core P-routers are completely hidden from customer traceroute.",
    category: "Diagnostics",
    presetId: "ttl_uniform_vs_pipe",
    learningPoints: [
      "Pipe mode encapsulates customer IP TTL without exposing internal provider topology.",
      "The entire MPLS core appears as a single 1-hop virtual link to the customer.",
      "Standard best practice for enterprise VPN service providers.",
    ],
  },
};
